//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.30 at 01:14:03 PM CDT 
//


package edu.umd.cs.guitar.model.data;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AttributesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AttributesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Property" type="{}PropertyType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AttributesType", propOrder = {
    "property"
})
@XmlRootElement(name = "Attributes")
public class AttributesType implements java.io.Serializable {

    @XmlElement(name = "Property", required = true)
    protected List<PropertyType> property;

    /**
     * Gets the value of the property property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the property property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProperty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PropertyType }
     * 
     * 
     */
    public List<PropertyType> getProperty() {
        if (property == null) {
            property = new ArrayList<PropertyType>();
        }
        return this.property;
    }

    /**
     * Sets the value of the property property.
     * 
     * @param property
     *     allowed object is
     *     {@link PropertyType }
     *     
     */
    public void setProperty(List<PropertyType> property) {
        this.property = property;
    }
    
    public String toString()
    {
    	if(property == null)
    		return "";
    	String toReturn = "";
    	
    	if(property.isEmpty())
    		return toReturn;
    	toReturn = printProperty(property.get(0));
    	for(int i = 1; i < property.size(); i++)
    		toReturn += "\n" + printProperty(property.get(i));
    			
//    	for(PropertyType p : property) { 
//    		
////    		toReturn += "Name: " + p.getName() + " Value: [" + p.getValue() + "]";  
//    		toReturn += "Name: " + p.getName() + " Value: [";
//    		if(p.getValue().size() != 0) {
//    			toReturn += p.getValue().get(0);
//    			for(int i = 0; i < p.getValue().size(); i++) 
//    				toReturn += ", " + p.getValue().get(i);
//    		}
//    		else 
//    			toReturn += "";
//    		toReturn += "]\n";
//    	}
//    	toReturn += "";
    	return toReturn;
    }
    
    private String printProperty(PropertyType p)
    {
    	String toReturn = "Name: " + p.getName() + " Value: [";
		if(p.getValue().size() != 0) {
			toReturn += p.getValue().get(0);
			for(int i = 0; i < p.getValue().size(); i++) 
				toReturn += ", " + p.getValue().get(i);
		}
		else 
			toReturn += "";
		toReturn += "]";
		return toReturn;
    }
}
