//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.16 at 03:20:19 PM CST 
//


package edu.umd.cs.guitar.model.data;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WidgetList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CogToolWidgetList">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CTW" type="{}CTW" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CogToolWidgetList", propOrder = {
    "ctw"
})
@XmlRootElement(name = "CogToolWidgets")
public class CogToolWidgetList implements Iterable<CTW>{

    @XmlElement(name = "CTW", required = true)
    protected List<CTW> ctw;

    /**
     * Gets the value of the ctw property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ctw property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCTW().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CTW }
     * 
     * 
     */
    public List<CTW> getCTW() {
        if (ctw == null) {
            ctw = new ArrayList<CTW>();
        }
        return this.ctw;
    }

    public Iterator<CTW> iterator()
    {
    	return getCTW().iterator();
    }
}
