//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.16 at 03:10:42 PM CST 
//


package edu.umd.cs.guitar.model.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CTW complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CTW">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IsStandard" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="shape" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="role" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="labelText" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="visible" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="extent" type="{}CTWExtent"/>
 *         &lt;element name="parent" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="selectedItemName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="isToggleable" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="isSelected" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="isSeparator" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CTW", propOrder = {
    "name",
    "isStandard",
    "shape",
    "role",
    "type",
    "labelText",
    "visible",
    "extent",
    "parent",
    "selectedItemName",
    "isToggleable",
    "isSelected",
    "isSeparator"
})
public class CTW {

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "IsStandard", defaultValue = "true")
    protected boolean isStandard;
    @XmlElement(required = true, defaultValue = "rectangle")
    protected String shape;
    @XmlElement(required = true)
    protected String role;
    @XmlElement(required = true)
    protected String type;
    @XmlElement(required = true)
    protected String labelText;
    protected boolean visible;
    @XmlElement(required = true)
    protected CTWExtent extent;
    @XmlElement(required = true)
    protected String parent;
    @XmlElement(required = true)
    protected String selectedItemName;
    protected boolean isToggleable;
    protected boolean isSelected;
    protected boolean isSeparator;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the isStandard property.
     * 
     */
    public boolean isIsStandard() {
        return isStandard;
    }

    /**
     * Sets the value of the isStandard property.
     * 
     */
    public void setIsStandard(boolean value) {
        this.isStandard = value;
    }

    /**
     * Gets the value of the shape property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShape() {
        return shape;
    }

    /**
     * Sets the value of the shape property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShape(String value) {
        this.shape = value;
    }

    /**
     * Gets the value of the role property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRole() {
        return role;
    }

    /**
     * Sets the value of the role property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRole(String value) {
        this.role = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the labelText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabelText() {
        return labelText;
    }

    /**
     * Sets the value of the labelText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabelText(String value) {
        this.labelText = value;
    }

    /**
     * Gets the value of the visible property.
     * 
     */
    public boolean isVisible() {
        return visible;
    }

    /**
     * Sets the value of the visible property.
     * 
     */
    public void setVisible(boolean value) {
        this.visible = value;
    }

    /**
     * Gets the value of the extent property.
     * 
     * @return
     *     possible object is
     *     {@link CTWExtent }
     *     
     */
    public CTWExtent getExtent() {
        return extent;
    }

    /**
     * Sets the value of the extent property.
     * 
     * @param value
     *     allowed object is
     *     {@link CTWExtent }
     *     
     */
    public void setExtent(CTWExtent value) {
        this.extent = value;
    }

    /**
     * Gets the value of the parent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParent() {
        return parent;
    }

    /**
     * Sets the value of the parent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParent(String value) {
        this.parent = value;
    }

    /**
     * Gets the value of the selectedItemName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSelectedItemName() {
        return selectedItemName;
    }

    /**
     * Sets the value of the selectedItemName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSelectedItemName(String value) {
        this.selectedItemName = value;
    }

    /**
     * Gets the value of the isToggleable property.
     * 
     */
    public boolean isToggleable() {
        return isToggleable;
    }

    /**
     * Sets the value of the isToggleable property.
     * 
     */
    public void setIsToggleable(boolean value) {
        this.isToggleable = value;
    }

    /**
     * Gets the value of the isSelected property.
     * 
     */
    public boolean isSelected() {
        return isSelected;
    }

    /**
     * Sets the value of the isSelected property.
     * 
     */
    public void setIsSelected(boolean value) {
        this.isSelected = value;
    }

    /**
     * Gets the value of the isSeparator property.
     * 
     */
    public boolean isSeparator() {
        return isSeparator;
    }

    /**
     * Sets the value of the isSeparator property.
     * 
     */
    public void setIsSeparator(boolean value) {
        this.isSeparator = value;
    }

}
