//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.18 at 10:44:22 AM CST 
//


package edu.umd.cs.guitar.model.data;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Order complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Order">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OrderGroup" type="{}OrderGroup" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Order", propOrder = {
    "orderGroup"
})
public class Order {

    @XmlElement(name = "OrderGroup", required = true)
    protected List<OrderGroup> orderGroup;

    /**
     * Gets the value of the orderGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the orderGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrderGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OrderGroup }
     * 
     * 
     */
    public List<OrderGroup> getOrderGroup() {
        if (orderGroup == null) {
            orderGroup = new ArrayList<OrderGroup>();
        }
        return this.orderGroup;
    }

    public String toString()
    {
    	if(orderGroup == null)
    		return "";
    	
    	String toReturn = "";
    	for(int i = 0; i < orderGroup.size(); i++)  
    		toReturn += (i+1) + "-\n" + orderGroup.get(i) + "\n";
    	
    	return toReturn;
    }
}
